# Generated by Django 6.1.1 on 2026-10-02 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('natureza', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=7)),
                ('tipo', models.CharField(choices=[('fixo', 'Fixo'), ('variavel', 'Variável')], max_length=8)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['natureza', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('tipo', models.CharField(choices=[('corrente', 'Corrente'), ('dinheiro', 'Dinheiro'), ('investimento', 'Investimento')], max_length=12)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('transferencia', 'Transferência')], max_length=13)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='nucleo.categoria')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='nucleo.conta')),
                ('conta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recebidas', to='nucleo.conta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('usuario', 'nome', 'natureza'), name='categoria_nome_unico_por_usuario', violation_error_message='Você já tem uma categoria com esse nome e natureza.'),
        ),
        migrations.AddConstraint(
            model_name='conta',
            constraint=models.UniqueConstraint(fields=('usuario', 'nome'), name='conta_nome_unico_por_usuario', violation_error_message='Você já tem uma conta com esse nome.'),
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['usuario', 'data'], name='nucleo_tran_usuario_e22bba_idx'),
        ),
        migrations.AddConstraint(
            model_name='transacao',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='transacao_valor_positivo', violation_error_message='O valor precisa ser maior que zero.'),
        ),
        migrations.AddConstraint(
            model_name='transacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('categoria__isnull', False), ('conta_destino__isnull', True), ('tipo__in', ['receita', 'despesa'])), models.Q(('categoria__isnull', True), ('conta_destino__isnull', False), ('tipo', 'transferencia')), _connector='OR'), name='transacao_campos_por_tipo', violation_error_message='Receita e despesa exigem categoria e não têm conta de destino; transferência exige conta de destino e não tem categoria.'),
        ),
        migrations.AddConstraint(
            model_name='transacao',
            constraint=models.CheckConstraint(condition=models.Q(('conta_destino', models.F('conta')), _negated=True), name='transacao_destino_diferente', violation_error_message='A conta de destino precisa ser diferente da conta de origem.'),
        ),
    ]
