# Generated by Django 6.1.1 on 2026-10-02 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('parcelas', models.PositiveSmallIntegerField(default=1)),
                ('data_compra', models.DateField()),
            ],
            options={
                'ordering': ['-data_compra', '-id'],
            },
        ),
        migrations.AddField(
            model_name='conta',
            name='dia_fechamento',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conta',
            name='dia_vencimento',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='numero_parcela',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='tipo',
            field=models.CharField(choices=[('corrente', 'Corrente'), ('dinheiro', 'Dinheiro'), ('investimento', 'Investimento'), ('cartao', 'Cartão de crédito')], max_length=12),
        ),
        migrations.AddConstraint(
            model_name='conta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dia_fechamento__gte', 1), ('dia_fechamento__isnull', False), ('dia_fechamento__lte', 31), ('dia_vencimento__gte', 1), ('dia_vencimento__isnull', False), ('dia_vencimento__lte', 31), ('tipo', 'cartao')), models.Q(models.Q(('tipo', 'cartao'), _negated=True), ('dia_fechamento__isnull', True), ('dia_vencimento__isnull', True)), _connector='OR'), name='conta_dias_so_no_cartao', violation_error_message='Cartão exige dia de fechamento e de vencimento entre 1 e 31; as outras contas não têm esses dias.'),
        ),
        migrations.AddField(
            model_name='compra',
            name='cartao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='nucleo.conta'),
        ),
        migrations.AddField(
            model_name='compra',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='nucleo.categoria'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transacao',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_geradas', to='nucleo.compra'),
        ),
        migrations.AddConstraint(
            model_name='transacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('compra__isnull', True), ('numero_parcela__isnull', True)), models.Q(('compra__isnull', False), ('numero_parcela__gte', 1), ('numero_parcela__isnull', False), ('tipo', 'despesa')), _connector='OR'), name='transacao_parcela_completa', violation_error_message='Parcela exige compra e número, e é sempre despesa.'),
        ),
        migrations.AddConstraint(
            model_name='transacao',
            constraint=models.UniqueConstraint(fields=('compra', 'numero_parcela'), name='transacao_parcela_unica'),
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total__gt', 0)), name='compra_valor_positivo', violation_error_message='O valor precisa ser maior que zero.'),
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.CheckConstraint(condition=models.Q(('parcelas__gte', 1)), name='compra_ao_menos_uma_parcela', violation_error_message='A compra precisa ter pelo menos uma parcela.'),
        ),
    ]
