# Generated by Django 6.1.1 on 2026-10-04 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_cartao_de_credito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='fatura_paga',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='transacao',
            constraint=models.CheckConstraint(condition=models.Q(('fatura_paga__isnull', True), ('tipo', 'transferencia'), _connector='OR'), name='transacao_pagamento_e_transferencia', violation_error_message='Pagamento de fatura é sempre uma transferência.'),
        ),
        migrations.AddConstraint(
            model_name='transacao',
            constraint=models.UniqueConstraint(condition=models.Q(('fatura_paga__isnull', False)), fields=('conta_destino', 'fatura_paga'), name='transacao_fatura_paga_uma_vez', violation_error_message='Esta fatura já foi paga.'),
        ),
    ]
