# Generated by Django 6.1.1 on 2026-10-04 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_pagamento_de_fatura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='competencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Recorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('transferencia', 'Transferência')], max_length=13)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dia', models.PositiveSmallIntegerField()),
                ('inicio', models.DateField()),
                ('fim', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorrencias', to='nucleo.categoria')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorrencias', to='nucleo.conta')),
                ('conta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorrencias_recebidas', to='nucleo.conta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorrencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dia', 'descricao'],
            },
        ),
        migrations.AddField(
            model_name='transacao',
            name='recorrencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmacoes', to='nucleo.recorrencia'),
        ),
        migrations.AddConstraint(
            model_name='transacao',
            constraint=models.CheckConstraint(condition=models.Q(('recorrencia__isnull', True), ('competencia__isnull', False), _connector='OR'), name='transacao_recorrencia_com_competencia', violation_error_message='Transação de recorrência exige o mês de competência.'),
        ),
        migrations.AddConstraint(
            model_name='transacao',
            constraint=models.UniqueConstraint(condition=models.Q(('recorrencia__isnull', False)), fields=('recorrencia', 'competencia'), name='transacao_recorrencia_uma_vez_por_mes', violation_error_message='Esta recorrência já foi confirmada neste mês.'),
        ),
        migrations.AddConstraint(
            model_name='recorrencia',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='recorrencia_valor_positivo', violation_error_message='O valor precisa ser maior que zero.'),
        ),
        migrations.AddConstraint(
            model_name='recorrencia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('categoria__isnull', False), ('conta_destino__isnull', True), ('tipo__in', ['receita', 'despesa'])), models.Q(('categoria__isnull', True), ('conta_destino__isnull', False), ('tipo', 'transferencia')), _connector='OR'), name='recorrencia_campos_por_tipo', violation_error_message='Receita e despesa exigem categoria e não têm conta de destino; transferência exige conta de destino e não tem categoria.'),
        ),
        migrations.AddConstraint(
            model_name='recorrencia',
            constraint=models.CheckConstraint(condition=models.Q(('conta_destino', models.F('conta')), _negated=True), name='recorrencia_destino_diferente', violation_error_message='A conta de destino precisa ser diferente da conta de origem.'),
        ),
        migrations.AddConstraint(
            model_name='recorrencia',
            constraint=models.CheckConstraint(condition=models.Q(('dia__gte', 1), ('dia__lte', 31)), name='recorrencia_dia_valido', violation_error_message='O dia precisa estar entre 1 e 31.'),
        ),
        migrations.AddConstraint(
            model_name='recorrencia',
            constraint=models.CheckConstraint(condition=models.Q(('inicio__day', 1), models.Q(('fim__isnull', True), models.Q(('fim__day', 1), ('fim__gte', models.F('inicio'))), _connector='OR')), name='recorrencia_periodo_valido', violation_error_message='Início e fim são meses, e o fim não pode ser antes do início.'),
        ),
    ]
