# Generated by Django 6.1.1 on 2026-10-04 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_recorrencias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inicio', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='nucleo.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['categoria__nome', '-inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='orcamento_valor_positivo', violation_error_message='O limite precisa ser maior que zero.'), models.CheckConstraint(condition=models.Q(('inicio__day', 1)), name='orcamento_inicio_e_um_mes', violation_error_message='O início é um mês (primeiro dia).'), models.UniqueConstraint(fields=('categoria', 'inicio'), name='orcamento_uma_vigencia_por_mes', violation_error_message='Esta categoria já tem um limite começando neste mês.')],
            },
        ),
    ]
