# Generated by Django 6.1.1 on 2026-10-04 05:21

from django.db import migrations, models

from nucleo.aparencia import ICONE_DA_CONTA, Icone, proxima_cor


def preencher_cadastros_existentes(apps, schema_editor):
    # Models "históricos" da migration não rodam o save() customizado: a regra vai aqui.
    # Cada usuário recebe as cores em ordem, pela ordem em que criou cada cadastro.
    for nome_do_model in ['Conta', 'Categoria']:
        Model = apps.get_model('nucleo', nome_do_model)
        posicao_por_usuario = {}
        for registro in Model.objects.order_by('id'):
            posicao = posicao_por_usuario.get(registro.usuario_id, 0)
            posicao_por_usuario[registro.usuario_id] = posicao + 1
            registro.cor = proxima_cor(posicao)
            if nome_do_model == 'Conta':
                registro.icone = ICONE_DA_CONTA[registro.tipo]
            else:
                registro.icone = Icone.ETIQUETA
            registro.save(update_fields=['cor', 'icone'])


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_orcamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='cor',
            field=models.CharField(blank=True, choices=[('azul', 'Azul'), ('laranja', 'Laranja'), ('turquesa', 'Turquesa'), ('amarelo', 'Amarelo'), ('rosa', 'Rosa'), ('verde', 'Verde'), ('violeta', 'Violeta'), ('vermelho', 'Vermelho')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='categoria',
            name='icone',
            field=models.CharField(blank=True, choices=[('casa', 'Casa'), ('carrinho', 'Carrinho'), ('refeicao', 'Refeição'), ('carro', 'Carro'), ('onibus', 'Ônibus'), ('saude', 'Saúde'), ('academia', 'Academia'), ('educacao', 'Educação'), ('lazer', 'Lazer'), ('viagem', 'Viagem'), ('roupa', 'Roupa'), ('presente', 'Presente'), ('pet', 'Pet'), ('celular', 'Celular'), ('internet', 'Internet'), ('energia', 'Energia'), ('agua', 'Água'), ('trabalho', 'Trabalho'), ('dinheiro', 'Dinheiro'), ('cofrinho', 'Cofrinho'), ('investimento', 'Investimento'), ('banco', 'Banco'), ('carteira', 'Carteira'), ('cartao', 'Cartão'), ('recibo', 'Recibo'), ('etiqueta', 'Etiqueta')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='conta',
            name='cor',
            field=models.CharField(blank=True, choices=[('azul', 'Azul'), ('laranja', 'Laranja'), ('turquesa', 'Turquesa'), ('amarelo', 'Amarelo'), ('rosa', 'Rosa'), ('verde', 'Verde'), ('violeta', 'Violeta'), ('vermelho', 'Vermelho')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='conta',
            name='icone',
            field=models.CharField(blank=True, choices=[('casa', 'Casa'), ('carrinho', 'Carrinho'), ('refeicao', 'Refeição'), ('carro', 'Carro'), ('onibus', 'Ônibus'), ('saude', 'Saúde'), ('academia', 'Academia'), ('educacao', 'Educação'), ('lazer', 'Lazer'), ('viagem', 'Viagem'), ('roupa', 'Roupa'), ('presente', 'Presente'), ('pet', 'Pet'), ('celular', 'Celular'), ('internet', 'Internet'), ('energia', 'Energia'), ('agua', 'Água'), ('trabalho', 'Trabalho'), ('dinheiro', 'Dinheiro'), ('cofrinho', 'Cofrinho'), ('investimento', 'Investimento'), ('banco', 'Banco'), ('carteira', 'Carteira'), ('cartao', 'Cartão'), ('recibo', 'Recibo'), ('etiqueta', 'Etiqueta')], default='', max_length=20),
        ),
        # Desfazer a migration apaga as colunas; não há nada a reverter nos dados
        migrations.RunPython(preencher_cadastros_existentes, migrations.RunPython.noop),
    ]
