import {
  Banknote,
  Briefcase,
  Bus,
  Car,
  CreditCard,
  Droplet,
  Dumbbell,
  Gamepad2,
  Gift,
  GraduationCap,
  HeartPulse,
  House,
  Landmark,
  PawPrint,
  PiggyBank,
  Plane,
  Receipt,
  Shirt,
  ShoppingCart,
  Smartphone,
  Tag,
  TrendingUp,
  Utensils,
  Wallet,
  Wifi,
  Zap,
  type LucideIcon,
} from 'lucide-react'

import type { NomeDoIcone } from '@/core/utils'

/** Liga cada nome de ícone guardado no backend ao desenho do Lucide. */
export const ICONES: Record<NomeDoIcone, LucideIcon> = {
  casa: House,
  carrinho: ShoppingCart,
  refeicao: Utensils,
  carro: Car,
  onibus: Bus,
  saude: HeartPulse,
  academia: Dumbbell,
  educacao: GraduationCap,
  lazer: Gamepad2,
  viagem: Plane,
  roupa: Shirt,
  presente: Gift,
  pet: PawPrint,
  celular: Smartphone,
  internet: Wifi,
  energia: Zap,
  agua: Droplet,
  trabalho: Briefcase,
  dinheiro: Banknote,
  cofrinho: PiggyBank,
  investimento: TrendingUp,
  banco: Landmark,
  carteira: Wallet,
  cartao: CreditCard,
  recibo: Receipt,
  etiqueta: Tag,
}
